### ISSUE TITLE
Fail gracefully for invalid payload (ERR_INVALID_ARG_TYPE)

### ISSUE THREAD

**Issue by beevelop** [tiagordc/node-red-contrib-simple-soap#7]
When accidentally setting the payload to an object, the module fails and kills the Node-RED instance. It would be awesome to handle this error gracefully and e.g. log via `node.error` / use the status with an error hint.

```
25 Jun 13:21:52 - TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
at write_ (_http_outgoing.js:595:11)
at ClientRequest.write (_http_outgoing.js:567:10)
at Request.write (/data/node_modules/node-red-contrib-simple-soap/node_modules/request/request.js:1500:27)
at end (/data/node_modules/node-red-contrib-simple-soap/node_modules/request/request.js:549:18)
at Immediate.<anonymous> (/data/node_modules/node-red-contrib-simple-soap/node_modules/request/request.js:578:7)
```

**Comment by nero408** [comment]
<a href="https://imgflip.com/i/46arxx"><img src="https://i.imgflip.com/46arxx.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by bastian1993** [comment]
I can confirm that, would be great to get better handling.
